# site properties and page defaults
title: Parekh Lab for Motivational, Affective, and Cognitive Systems @ UT Dallas
subtitle: BBS - Department of Neuroscience
description: 
header: images/ACC_histo.jpg
footer: images/BBS.jpeg
proofer: false 

# site social media and other links
links:
  email: pkp240000@utdallas.edu
  orcid: 0000-0002-4158-2305
  google-scholar: q3QMX5kAAAAJ
  github: 
  twitter: _droctothorpe_

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
